#!/bin/bash

#give permission for everything in the express-app directory
sudo chmod -R 755 /home/ec2-user/Test_node_CICD

#navigate into our working directory where we have all our github files
cd /home/ec2-user/Test_node_CICD

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
. ~/.nvm/nvm.sh
nvm install node


#install node modules
npm install

#start our node app in the background
node app.js